spring.application.name=cradlenotes
aws.accessKeyId= AKIA4U3OTFAYJJT6QJRR
aws.secretKey=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
aws.region=us-east-2
aws.s3.bucket=cradlenotesbackup-nishat--use2-az1--x-s3